---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv
  labels:
    type: local
    app: mysql-backup
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/mysql-backups"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: devops-case-study
  labels:
    app: mysql-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""  # Bind to manual PV
  selector:
    matchLabels:
      type: local
      app: mysql-backup
