apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-verify-job
  namespace: devops-case-study
  labels:
    app: mysql-verify
spec:
  template:
    metadata:
      labels:
        app: mysql-verify-job
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-verify
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          chmod +x /scripts/verify.sh
          /scripts/verify.sh
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        volumeMounts:
        - name: backup-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: backup-scripts
        configMap:
          name: mysql-backup-script
          defaultMode: 0755
  backoffLimit: 3
