{{- if .Values.pss.baseline.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-capabilities
  labels:
    {{- include "pss-policies.labels" . | nindent 4 }}
  annotations:
    {{- include "pss-policies.annotations" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Disallow Capabilities
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/subject: Pod
    policies.nirmata.io/remediation-docs: "https://docs.nirmata.io/policysets/podsecurity/baseline/disallow-capabilities/"
    policies.kyverno.io/description: >-
      Any additional capabilities not mentioned in the allowed list, which includes AUDIT_WRITE, CHOWN, DAC_OVERRIDE, FOWNER, FSETID, KILL, MKNOD, NET_BIND_SERVICE, SETFCAP, SETGID, SETPCAP, SETUID, SYS_CHROOT, are prohibited and not permitted.
spec:
  validationFailureAction: {{ include "pss-policies.validationFailureAction" (dict "Values" .Values "policyName" "disallow-capabilities") }}
  background: {{ include "pss-policies.background" (dict "Values" .Values "policyName" "disallow-capabilities") }}
  admission: {{ .Values.pss.admission }}
  emitWarning: {{ .Values.pss.emitWarning }}
  rules:
    - name: adding-capabilities
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - kube-system
            - nirmata
            - nirmata-system
            - kyverno
      context:
      - name: AllowedCapabilities
        variable:
          value: 
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
      validate:
        message: >-
          Any capabilities added beyond the allowed list (AUDIT_WRITE, CHOWN, DAC_OVERRIDE, FOWNER, FSETID, KILL, MKNOD, NET_BIND_SERVICE, SETFCAP, SETGID, SETPCAP, SETUID, SYS_CHROOT) are disallowed.
        deny:
          conditions:
            all:
              - key: {{ `"{{ request.object.spec.[ephemeralContainers, initContainers, containers][].securityContext.capabilities.add[] }}"` }}
                operator: AnyNotIn
                value: {{ `"{{ AllowedCapabilities }}"` }}




{{- end }}
