{{- if .Values.pss.baseline.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-seccomp
  labels:
    {{- include "pss-policies.labels" . | nindent 4 }}
  annotations:
    {{- include "pss-policies.annotations" . | nindent 4 }}
    policies.kyverno.io/title: Restrict Seccomp
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.nirmata.io/remediation-docs: "https://docs.nirmata.io/policysets/podsecurity/baseline/restrict-seccomp/"
    policies.kyverno.io/description: >-
      The seccomp profile must not be explicitly set to Unconfined. This policy,
      requiring Kubernetes v1.19 or later, ensures that the fields
      spec.securityContext.seccompProfile.type,
      spec.containers[*].securityContext.seccompProfile.type,
      spec.initContainers[*].securityContext.seccompProfile.type, and
      spec.ephemeralContainers[*].securityContext.seccompProfile.type
      must be unset or set to `RuntimeDefault` or `Localhost`.
spec:
  validationFailureAction: {{ include "pss-policies.validationFailureAction" (dict "Values" .Values "policyName" "restrict-seccomp") }}
  background: {{ include "pss-policies.background" (dict "Values" .Values "policyName" "restrict-seccomp") }}
  admission: {{ .Values.pss.admission }}
  emitWarning: {{ .Values.pss.emitWarning }}
  rules:
    - name: check-seccomp
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - kube-system
            - nirmata
            - nirmata-system
            - kyverno
      validate:
        message: >-
          Use of custom Seccomp profiles is disallowed. The fields spec.securityContext.seccompProfile.type, spec.containers[*].securityContext.seccompProfile.type, spec.initContainers[*].securityContext.seccompProfile.type, and spec.ephemeralContainers[*].securityContext.seccompProfile.type must be unset or set to RuntimeDefault or Localhost.
        pattern:
          spec:
            =(securityContext):
              =(seccompProfile):
                =(type): "RuntimeDefault | Localhost"
            =(ephemeralContainers):
              - =(securityContext):
                  =(seccompProfile):
                    =(type): "RuntimeDefault | Localhost"
            =(initContainers):
              - =(securityContext):
                  =(seccompProfile):
                    =(type): "RuntimeDefault | Localhost"
            containers:
              - =(securityContext):
                  =(seccompProfile):
                    =(type): "RuntimeDefault | Localhost"
{{- end }}
