{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-pv
  labels:
    type: local
    app: mysql
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.mysql.size }}
  accessModes:
    - {{ .Values.persistence.mysql.accessMode }}
  hostPath:
    path: "/tmp/data/mysql"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-pvc
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.mysql.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size }}
  storageClassName: ""  # Disable dynamic provisioning to bind to manual PV
  selector:
    matchLabels:
      type: local
      app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-secret
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.database.mysql.auth.rootPassword | b64enc }}
  mysql-user: {{ .Values.database.mysql.auth.username | b64enc }}
  mysql-password: {{ .Values.database.mysql.auth.password | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-config
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
data:
  mysql.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    port = 3306
    datadir = /var/lib/mysql
    socket = /var/run/mysqld/mysqld.sock
    pid-file = /var/run/mysqld/mysqld.pid
    log-error = /var/log/mysql/error.log
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    max_connections = 100
    innodb_buffer_pool_size = 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devops-case-study.database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-case-study.database.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "devops-case-study.fullname" . }}-mysql-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "devops-case-study.fullname" . }}-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "devops-case-study.fullname" . }}-mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          value: {{ .Values.database.mysql.auth.database | quote }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.database.mysql.primary.resources | nindent 10 }}
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ include "devops-case-study.fullname" . }}-mysql-pvc
      - name: mysql-config
        configMap:
          name: {{ include "devops-case-study.fullname" . }}-mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-service
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "devops-case-study.database.selectorLabels" . | nindent 4 }}
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
{{- end }}
