{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devops-case-study.fullname" . }}-mysql-network-policy
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.database.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: mysql
      tier: database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow connections from web-server pods to MySQL port 3306
  - from:
    - podSelector:
        matchLabels:
          app: web-server
          tier: frontend
    ports:
    - protocol: TCP
      port: 3306
  # Allow connections from monitoring pods (for health checks)
  - from:
    - podSelector:
        matchLabels:
          app: pod-monitor
    ports:
    - protocol: TCP
      port: 3306
  # Allow DNS resolution
  - from: []
    ports:
    - protocol: UDP
      port: 53
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow responses back to web-server pods
  - to:
    - podSelector:
        matchLabels:
          app: web-server
          tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devops-case-study.fullname" . }}-web-server-network-policy
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.webServer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: web-server
      tier: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow HTTP traffic from anywhere (for the web interface)
  - from: []
    ports:
    - protocol: TCP
      port: 80
  # Allow monitoring traffic
  - from:
    - podSelector:
        matchLabels:
          app: pod-monitor
    ports:
    - protocol: TCP
      port: 80
  egress:
  # Allow connections to MySQL database
  - to:
    - podSelector:
        matchLabels:
          app: mysql
          tier: database
    ports:
    - protocol: TCP
      port: 3306
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS outbound (for potential external API calls)
  - to: []
    ports:
    - protocol: TCP
      port: 443
---
{{- if .Values.networkPolicies.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devops-case-study.fullname" . }}-default-deny-ingress
  namespace: {{ include "devops-case-study.namespace" . }}
  labels:
    {{- include "devops-case-study.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}
