apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webServer.service.type }}
  selector:
    {{- include "web-server.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.webServer.service.port }}
    targetPort: {{ .Values.webServer.service.targetPort }}
    protocol: TCP
    name: http
