apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-case-study-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-case-study-apps
    app.kubernetes.io/part-of: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/musical-giggle.git
    targetRevision: gitops
    path: argocd-apps
    directory:
      recurse: true
      include: "*-app.yaml"
      exclude: "app-of-apps.yaml"  # Prevent recursive loop
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
