apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: security
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: "3.2.6"  # Latest stable version
    helm:
      releaseName: kyverno
      values: |
        # Kyverno Configuration for Policy-as-Code Security
        
        # CRITICAL: ArgoCD Configuration (per Kyverno docs)
        config:
          preserve: false  # Essential for ArgoCD deployments!
        
        # Webhook labels for ArgoCD tracking
        webhookLabels:
          app.kubernetes.io/managed-by: argocd
        
        # Resource configuration
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi" 
            cpu: "50m"
        
        # Enable policy reports for compliance monitoring
        policyReports:
          enabled: true
        
        # Enable background scanning
        backgroundController:
          enabled: true
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "50m"
        
        # Enable cleanup controller
        cleanupController:
          enabled: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
        
        # Enable reports controller
        reportsController:
          enabled: true
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "50m"
        
        # Security settings
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        
        # Service account
        serviceAccount:
          create: true
          annotations: {}
        
        # RBAC
        rbac:
          create: true
          serviceAccount:
            create: true
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
