apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - post-delete-finalizer.argocd.argoproj.io
    - post-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/devops-k8s-case-study.git
    targetRevision: workflows
    path: helm-charts/kyverno
    helm:
      valueFiles:
        - values.yaml
      values: |
        # Speed up background processing for generateExisting policies
        backgroundController:
          extraEnvVars:
            - name: BACKGROUND_SCAN_INTERVAL
              value: "1m"  # Scan every 1 minute instead of default 5 minutes
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1.reports.kyverno.io
      jsonPointers:
        - /spec
        - /metadata
        - /status
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1alpha2.wgpolicyk8s.io
      jsonPointers:
        - /spec
        - /metadata
        - /status
    - group: apps
      kind: StatefulSet
      name: etcd
      namespace: kyverno
      jsonPointers:
        - /spec/template/metadata
        - /spec/template/spec
        - /metadata/annotations
        - /metadata/labels
        - /spec/volumeClaimTemplates
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
        - /spec/persistentVolumeClaimRetentionPolicy
        - /status
    - group: batch
      kind: Job
      name: reports-server-post-install-install-api-services
      namespace: kyverno
      jsonPointers:
        - /spec
        - /metadata
        - /status