apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: devops-case-study
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/devops-k8s-case-study.git
    targetRevision: main
    path: helm-charts/monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-case-study
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
