apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reports-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anuddeeph1/musical-giggle.git
    targetRevision: gitops
    path: helm-charts/reports-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - DisableOpenAPIValidation=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1.reports.kyverno.io
      jsonPointers:
        - /spec
        - /metadata
        - /status
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1alpha2.wgpolicyk8s.io
      jsonPointers:
        - /spec
        - /metadata
        - /status
    - group: apps
      kind: StatefulSet
      name: etcd
      namespace: kyverno
      jsonPointers:
        - /spec/template/metadata
        - /spec/template/spec
        - /metadata/annotations
        - /metadata/labels
        - /spec/volumeClaimTemplates
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
        - /spec/persistentVolumeClaimRetentionPolicy
        - /status
    - group: batch
      kind: Job
      name: reports-server-post-install-install-api-services
      namespace: kyverno
      jsonPointers:
        - /spec
        - /metadata
        - /status
