# Nginx Web Server Configuration
global:
  namespace: devops-case-study

webServer:
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  
  replicas: 3
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  
  ingress:
    enabled: true
    host: localhost
    path: /
  
  resources:
    requests:
      memory: "40Mi"
      cpu: "20m"
    limits:
      memory: "60Mi"
      cpu: "40m"

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 20
    targetMemoryUtilizationPercentage: 35

  nodeSelector: {}
  tolerations: []
  affinity: {}

monitoring:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    additionalLabels: {}
    metricRelabelings: []
    relabelings: []
