{{- if .Values.pss.restricted.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root-user
  labels:
    {{- include "pss-policies.labels" . | nindent 4 }}
  annotations:
    {{- include "pss-policies.annotations" . | nindent 4 }}
    policies.kyverno.io/title: Require Run As Non-Root User
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.nirmata.io/remediation-docs: "https://docs.nirmata.io/policysets/podsecurity/restricted/require-run-as-non-root-user/"
    policies.kyverno.io/description: >-
      Containers must be required to run as non-root users. This policy ensures that the fields
      spec.securityContext.runAsUser,
      spec.containers[*].securityContext.runAsUser, spec.initContainers[*].securityContext.runAsUser,
      and spec.ephemeralContainers[*].securityContext.runAsUser is either unset or
      set to a number greater than zero.
spec:
  validationFailureAction: {{ include "pss-policies.validationFailureAction" (dict "Values" .Values "policyName" "require-run-as-non-root-user") }}
  background: {{ include "pss-policies.background" (dict "Values" .Values "policyName" "require-run-as-non-root-user") }}
  admission: {{ .Values.pss.admission }}
  emitWarning: {{ .Values.pss.emitWarning }}
  rules:
    - name: run-as-non-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - kube-system
            - nirmata
            - nirmata-system
            - kyverno
      validate:
        message: >-
          Running containers as root user (UID 0) is not allowed. The fields spec.securityContext.runAsUser, spec.containers[*].securityContext.runAsUser, spec.initContainers[*].securityContext.runAsUser, and spec.ephemeralContainers[*].securityContext.runAsUser must be unset or set to a number greater than zero.
        pattern:
          spec:
            =(securityContext):
              =(runAsUser): ">0"
            =(ephemeralContainers):
              - =(securityContext):
                  =(runAsUser): ">0"
            =(initContainers):
              - =(securityContext):
                  =(runAsUser): ">0"
            containers:
              - =(securityContext):
                  =(runAsUser): ">0"
{{- end }}

