# Pod Monitoring Configuration
global:
  namespace: devops-case-study

monitoring:
  podMonitor:
    image:
      repository: anuddeeph/pod-monitor
      tag: "latest-17459101307-29"
      pullPolicy: Always
    
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
    
    nodeSelector: {}
    tolerations: []
    affinity: {}
