# MySQL Database Configuration
global:
  namespace: devops-case-study

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  rootPassword: root123
  database: testdb
  user: testuser
  password: testpass
  
  service:
    type: ClusterIP
    port: 3306
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Backup Configuration
  backup:
    enabled: true
    storage:
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: ""
    
    # CronJob Configuration
    schedule: "0 */6 * * *"  # Every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
    retentionDays: 7         # Keep backups for 7 days
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    
    # Backup Job Resources
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

  nodeSelector: {}
  tolerations: []
  affinity: {}
