# MySQL Database Configuration
global:
  namespace: devops-case-study

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  rootPassword: root123
  database: testdb
  user: testuser
  password: testpass
  
  service:
    type: ClusterIP
    port: 3306
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Backup Configuration
  backup:
    enabled: true
    storage:
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: ""

  nodeSelector: {}
  tolerations: []
  affinity: {}
