{{- if .Values.mysql.backup.enabled }}
# This template creates a database verification job when applied  
# Usage: kubectl apply -f this-template-output.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "database.fullname" . }}-verify-job
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app.kubernetes.io/component: verify
spec:
  template:
    metadata:
      labels:
        {{- include "database.labels" . | nindent 8 }}
        app.kubernetes.io/component: verify-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-verify
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          chmod +x /scripts/verify.sh
          /scripts/verify.sh
        env:
        - name: MYSQL_HOST
          value: "{{ include "database.fullname" . }}-service"
        - name: MYSQL_PORT
          value: "{{ .Values.mysql.service.port }}"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database.fullname" . }}-secret
              key: mysql-root-password
        volumeMounts:
        - name: backup-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: backup-scripts
        configMap:
          name: {{ include "database.fullname" . }}-backup-script
          defaultMode: 0755
      {{- with .Values.mysql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
