apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
    app: mysql
    app.kubernetes.io/name: {{ include "database.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.size }}
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  hostPath:
    path: "/tmp/data/mysql"
  persistentVolumeReclaimPolicy: Retain
