apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-user: {{ .Values.mysql.user | b64enc }}
  mysql-password: {{ .Values.mysql.password | b64enc }}
  mysql-database: {{ .Values.mysql.database | b64enc }}
