apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: 3306
    protocol: TCP
    name: mysql
