apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: load-tester-role
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "load-testing.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: load-tester-binding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "load-testing.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: load-tester-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: load-tester-role
  apiGroup: rbac.authorization.k8s.io
