apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-tester-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "load-testing.labels" . | nindent 4 }}
automountServiceAccountToken: true
